# Generated by Django 2.0.5 on 2018-05-27 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estabelecimento',
            old_name='name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='predio',
            old_name='name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='sala',
            old_name='name',
            new_name='nome',
        ),
    ]
