# Generated by Django 2.0.5 on 2018-06-20 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_contato'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contato',
        ),
    ]
