# Generated by Django 2.0.5 on 2018-05-27 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_auto_20180527_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predio',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
