# Generated by Django 2.0.5 on 2018-05-28 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_auto_20180527_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumo',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='predio',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sala',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
