# Generated by Django 2.0.5 on 2018-05-28 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_auto_20180527_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumo',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
        migrations.AlterField(
            model_name='estabelecimento',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
        migrations.AlterField(
            model_name='predio',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sala',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
    ]
