# Generated by Django 2.0.5 on 2019-02-10 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_auto_20190210_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='estabelecimento',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
