# Generated by Django 2.0.5 on 2018-05-28 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0006_auto_20180527_2347'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='predio',
            unique_together={('estabelecimento', 'nome')},
        ),
        migrations.AlterUniqueTogether(
            name='sala',
            unique_together={('predio', 'nome')},
        ),
    ]
