# Generated by Django 2.0.5 on 2019-02-11 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0006_auto_20190211_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumo',
            name='estabelecimento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sistema.Estabelecimento'),
            preserve_default=False,
        ),
    ]
