# Generated by Django 2.0.5 on 2018-05-28 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0007_auto_20180527_2355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumo',
            old_name='kWh',
            new_name='kwh',
        ),
    ]
