# Generated by Django 2.0.5 on 2019-02-14 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0008_estabelecimento_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estabelecimento',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
