# Generated by Django 2.0.5 on 2019-03-19 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0009_auto_20190213_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumo',
            name='data',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
